### ISSUE TITLE
Incorrect Icons in Settngs

### ISSUE THREAD

**Issue by FiyreWyrkz** [Zerthox/Material-Icon-Theme#1]
It would appear that, likely, since the addition of Nitro that the ordering of the icons in the settings area are now incorrect. Thanks for any fix.

![image](https://cloud.githubusercontent.com/assets/1255952/23095293/f78ce900-f5cc-11e6-868f-c4ab307fe922.png)

**Comment by favna** [comment]
The correct list for settings is as follows:

```css
.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(2):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/person.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(3):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/broken_image.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(4):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/wifi.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(5):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/group.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(6):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/chat.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(7):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/mic.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(8):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/notifications.svg);
}

.platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(9):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(9):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/keyboard.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(10):after, .platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(10):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(10):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/camera.svg);
}

.platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(11):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(11):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/games.svg);
}

.platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(12):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/desktop_windows.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(13):after, .platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(13):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(13):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/place.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(14):after, .platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(14):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(14):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/videocam.svg);
}

.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(15):after, .platform-win .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(15):after, .platform-osx .user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(15):after {
    content: url(https://cdn.rawgit.com/Zerthox/Material-Icon-Theme/master/icons/security.svg);
}
```

This also puts the "broken_image.svg" at Nitro until creator adds a Nitro icon, which if he wants could in fact be this:

[nitro.zip](https://github.com/Zerthox/Material-Icon-Theme/files/785669/nitro.zip)

![nitro](https://cloud.githubusercontent.com/assets/4019718/23100816/dccd646a-f689-11e6-91a6-33b4c628ed6a.png)
